baseURL = 'http://gohugo.io/'
languageCode = 'en-us'
theme = "hugo-theme-rose-pine"
paginate = 5

[menu]
  [[menu.header]]
    name = "about"
    url = "about"
  [[menu.header]]
    name = "posts"
    url = "posts"
  [[menu.header]]
    name = "notes"
    url = "notes"


[params]
author = "Rose Pine"
user = "hello"
hostname = "rose.pine"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.example.com"

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"
